import { Plant, GrowthStage, HealthStatus } from './types';

const generateHistory = (startValue: number, days: number, growthRate: number) => {
  const history = [];
  let currentValue = startValue;
  for (let i = 0; i < days; i++) {
    const randomFlux = (Math.random() - 0.2) * 2;
    currentValue += growthRate + randomFlux;
    history.push({
      date: `Day ${i + 1}`,
      value: Number(currentValue.toFixed(0))
    });
  }
  return history;
};

export const MOCK_PLANTS: Plant[] = [
  {
    id: '1',
    name: 'Bird of Paradise',
    scientificName: 'Strelitzia reginae',
    description: 'A stunning tropical plant known for its banana-like leaves and bird-shaped flowers. It adds a lush, exotic feel to any space and gains value as it reaches flowering maturity.',
    image: 'https://images.unsplash.com/photo-1596728328738-95e263c9594f?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Growing,
    health: HealthStatus.Excellent,
    plantedDate: '2023-11-15',
    currentHeightCm: 45,
    maxHeightCm: 180,
    growthPercentage: 35,
    purchasePrice: 450,
    currentValue: 620,
    expectedValue30Days: 680,
    valueHistory: generateHistory(450, 45, 3.5),
    waterFrequency: 'Every 7-10 days',
    sunlightNeeds: 'Bright, indirect light',
    soilType: 'Well-draining, loamy',
    humidityLevel: 'High (60-70%)',
    variants: [
      {
        id: '1-a',
        sku: 'BOP-291',
        image: 'https://images.unsplash.com/photo-1596728328738-95e263c9594f?q=80&w=800&auto=format&fit=crop',
        currentHeightCm: 45,
        currentValue: 620,
        health: HealthStatus.Excellent,
        traits: ['Symmetrical', 'New Leaf'],
        matches: 98
      }
    ]
  },
  {
    id: '2',
    name: 'Monstera Albo',
    scientificName: 'Monstera deliciosa variegata',
    description: 'The crown jewel of any collection. Famous for its striking white and green variegation. Each leaf is a unique work of art.',
    image: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Seedling,
    health: HealthStatus.Healthy,
    plantedDate: '2024-01-10',
    currentHeightCm: 15,
    maxHeightCm: 250,
    growthPercentage: 12,
    purchasePrice: 300,
    currentValue: 340,
    expectedValue30Days: 390,
    valueHistory: generateHistory(300, 20, 2),
    waterFrequency: 'Every 5-7 days',
    sunlightNeeds: 'Moderate, indirect light',
    soilType: 'Peat-based potting soil',
    humidityLevel: 'Medium (40-60%)',
    variants: [
      {
        id: '2-a',
        sku: 'MON-101',
        image: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?q=80&w=800&auto=format&fit=crop',
        currentHeightCm: 15,
        currentValue: 340,
        health: HealthStatus.Healthy,
        traits: ['Half-Moon', 'High Variegation'],
        matches: 95
      }
    ]
  },
  {
    id: '3',
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    description: 'A popular indoor tree with large, heavily veined, violin-shaped leaves. A mature Fiddle Leaf Fig is a statement piece.',
    image: 'https://images.unsplash.com/photo-1610496525455-d14fb6195861?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Mature,
    health: HealthStatus.Excellent,
    plantedDate: '2023-05-20',
    currentHeightCm: 120,
    maxHeightCm: 300,
    growthPercentage: 85,
    purchasePrice: 800,
    currentValue: 1450,
    expectedValue30Days: 1500,
    valueHistory: generateHistory(800, 90, 7),
    waterFrequency: 'When top inch is dry',
    sunlightNeeds: 'Bright, filtered light',
    soilType: 'Nutrient-rich, well-draining',
    humidityLevel: 'Average (40-50%)',
    variants: []
  },
  {
    id: '4',
    name: 'Rubber Plant Burgundy',
    scientificName: 'Ficus elastica',
    description: 'Glossy, dark burgundy leaves that look almost black. A sophisticated addition to modern interiors.',
    image: 'https://images.unsplash.com/photo-1598880940086-537a5d901f4e?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Growing,
    health: HealthStatus.Excellent,
    plantedDate: '2023-09-01',
    currentHeightCm: 30,
    maxHeightCm: 90,
    growthPercentage: 40,
    purchasePrice: 200,
    currentValue: 280,
    expectedValue30Days: 295,
    valueHistory: generateHistory(200, 60, 1.3),
    waterFrequency: 'Every 2-3 weeks',
    sunlightNeeds: 'Low to bright indirect',
    soilType: 'Sandy, free-draining',
    humidityLevel: 'Low (Home average)'
  },
  {
    id: '5',
    name: 'Olive Tree',
    scientificName: 'Olea europaea',
    description: 'Mediterranean charm for your living room. Silvery-green foliage that symbolizes peace and wisdom.',
    image: 'https://images.unsplash.com/photo-1601614725064-1da603df50f3?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Growing,
    health: HealthStatus.Healthy,
    plantedDate: '2024-02-15',
    currentHeightCm: 60,
    maxHeightCm: 200,
    growthPercentage: 25,
    purchasePrice: 550,
    currentValue: 550,
    expectedValue30Days: 580,
    valueHistory: [{ date: 'Today', value: 550 }],
    waterFrequency: 'Moderate',
    sunlightNeeds: 'Full sun',
    soilType: 'Well-draining',
    humidityLevel: 'Low'
  },
  {
    id: '6',
    name: 'ZZ Plant Raven',
    scientificName: 'Zamioculcas zamiifolia',
    description: 'The indestructible plant with a goth twist. New leaves emerge bright green and mature to a deep, shiny black.',
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?q=80&w=800&auto=format&fit=crop',
    category: 'Plants',
    stage: GrowthStage.Growing,
    health: HealthStatus.Excellent,
    plantedDate: '2023-12-01',
    currentHeightCm: 25,
    maxHeightCm: 60,
    growthPercentage: 30,
    purchasePrice: 180,
    currentValue: 220,
    expectedValue30Days: 240,
    valueHistory: generateHistory(180, 45, 1),
    waterFrequency: 'Rarely',
    sunlightNeeds: 'Low light',
    soilType: 'Cactus mix',
    humidityLevel: 'Low'
  },
  {
    id: '7',
    name: 'Heirloom Tomato Seeds',
    scientificName: 'Solanum lycopersicum',
    description: 'Rare organic seeds for growing giant heirloom tomatoes. Perfect for summer gardening enthusiasts.',
    image: 'https://images.unsplash.com/photo-1592478411213-61535fdd861d?q=80&w=800&auto=format&fit=crop',
    category: 'Seeds',
    stage: GrowthStage.Seedling,
    health: HealthStatus.Excellent,
    plantedDate: '2024-03-01',
    currentHeightCm: 0,
    maxHeightCm: 150,
    growthPercentage: 0,
    purchasePrice: 25,
    currentValue: 25,
    expectedValue30Days: 25,
    valueHistory: [{ date: 'Today', value: 25 }],
    waterFrequency: 'Keep moist',
    sunlightNeeds: 'Full Sun',
    soilType: 'Seed starter mix',
    humidityLevel: 'High'
  },
  {
    id: '8',
    name: 'Ceramic Minimalist Pot',
    scientificName: 'Handcrafted',
    description: 'A premium white ceramic pot with drainage holes and saucer. Designed for modern interiors.',
    image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?q=80&w=800&auto=format&fit=crop',
    category: 'Pots',
    stage: GrowthStage.Mature,
    health: HealthStatus.Excellent,
    plantedDate: '2024-01-01',
    currentHeightCm: 20,
    maxHeightCm: 20,
    growthPercentage: 100,
    purchasePrice: 150,
    currentValue: 150,
    expectedValue30Days: 150,
    valueHistory: [{ date: 'Today', value: 150 }],
    waterFrequency: 'N/A',
    sunlightNeeds: 'N/A',
    soilType: 'Ceramic',
    humidityLevel: 'N/A'
  },
  {
    id: '9',
    name: 'Luxury Gift Hamper',
    scientificName: 'Assorted',
    description: 'A curated box containing a small succulent, a pot, and gardening tools. The perfect corporate gift.',
    image: 'https://images.unsplash.com/photo-1512428814795-a2741d571166?q=80&w=800&auto=format&fit=crop',
    category: 'Gifting',
    stage: GrowthStage.Mature,
    health: HealthStatus.Excellent,
    plantedDate: '2024-01-01',
    currentHeightCm: 0,
    maxHeightCm: 0,
    growthPercentage: 100,
    purchasePrice: 999,
    currentValue: 999,
    expectedValue30Days: 999,
    valueHistory: [{ date: 'Today', value: 999 }],
    waterFrequency: 'N/A',
    sunlightNeeds: 'N/A',
    soilType: 'N/A',
    humidityLevel: 'N/A'
  }
];